minishop_backend:
    resource: "@MinishopBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

minishop_user:
    resource: "@MinishopUserBundle/Resources/config/routing.yml"
    prefix:   /

minishop_shop:
    resource: "@MinishopShopBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login



#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
