minishop_backend:
    resource: "@MinishopBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

minishop_user:
    resource: "@MinishopUserBundle/Resources/config/routing.yml"
    prefix:   /user

minishop_shop:
    resource: "@MinishopShopBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

minishop_shop_api:
    resource: "@MinishopShopBundle/Controller/Api"
    type:     annotation
#    prefix:   /api

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
