# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.slugger:
        class: Minishop\ShopBundle\Utils\Slugger
        #how to use it $this->get('app.slugger')->slugify($post->getTitle());
    app.provider.oauth:
        class: Minishop\UserBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager, {facebook: facebookID, google: googleID}]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


