# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.slugger:
        class: Minishop\ShopBundle\Utils\Slugger
        #how to use it $this->get('app.slugger')->slugify($post->getTitle());
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


