<?php

namespace Minishop\ShopBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
  public function getProductWithCategory()
  {
    $productQuery = $this->getEntityManager()->createQuery(
            'SELECT p, c FROM MinishopShopBundle:Product p
             JOIN p.category c ORDER BY p.category ASC, p.id'
        );
    return $productQuery->getResult();
  }
}
