minishop_shop_category:
    resource: "@MinishopShopBundle/Resources/config/routing/category.yml"
    prefix:   /category

minishop_shop_product:
    resource: "@MinishopShopBundle/Resources/config/routing/product.yml"
    prefix:   /



#get_products:
#    path:     /api
#    defaults: { _controller: MinishopShopBundle:ProductApi:getProducts }
