minishop_shop_category:
    resource: "@MinishopShopBundle/Resources/config/routing/category.yml"
    prefix:   /category

minishop_shop_product:
    resource: "@MinishopShopBundle/Resources/config/routing/product.yml"
    prefix:   /

minishop_shop_product_api:
    resource: "@MinishopShopBundle/Controller/Api"
    prefix:   /api
    type:     annotation
